### ISSUE TITLE
Enable Jacko in blue

### ISSUE THREAD

**Issue by gogins** [gogins/plugins#3]
First I disabled all audio, MIDI, and Jack options in blue itself, as the Jacko opcodes should handle all of that. Then I ran:

- [x] @tjingboem's `RunMichael.blue`.
- [x] Importing the `jacko_test.csd` into blue.

The results were the same in both cases: 

1. The Jack connections show up properly in the QjackCtl graph window.
2. As soon as a note should play, blue crashes with a segmentation fault:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f508f801dd8, pid=8490, tid=8610
#
# JRE version: OpenJDK Runtime Environment (11.0.20.1+1) (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libcsoundjni.so+0x1dd8]  jniMessageStringCallback(CSOUND_*, int, char const*)+0x58
```

**Comment by gogins** [comment]
I tried changing all `csoundMessage` output to `std::fprintf(stderr` but no help.

**Comment by gogins** [comment]
I managed to get a backtrace of the crash using apport, but no help.

**Comment by gogins** [comment]
The only thing I can think of to try at this point is to look closely at all logging in jacko.cpp and test for potential crashes before printing anything.

**Comment by gogins** [comment]
I couldn't install the Adoptium Java SDK recommended by @kunstmusik. I upgraded my installation of Java `openjdk-18`.

**Comment by tjingboem** [comment]
This is my Java version:
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)

**Comment by gogins** [comment]
Rebuilding Jacko with: `cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_FLTK=false -DBUILD_ABLETON_LINK_OPCODES=false -DBUILD_STK_OPCODES=false`

**Comment by gogins** [comment]
I have found two installations of Csound on my Linux computer: an older one from the csound packages, and a newer one from `make install`. I'm trying:

1. sudo apt remove csound, etc.
2. cmake, make clean, make, sudo make install.

**Comment by gogins** [comment]
When I run the temporary .csd saved by blue when trying to run `jacko_test.blue`, the results are identical to running the original `csound jacko_test.csd`, as it should be. 

This proves the problem is caused by _how_ blue is trying to run `jacko_test.blue`.

I will try completely overriding options for the Csound API run. _That didn't help._

I must conclude there is a bug in the Java interface to Csound used by blue, or in the way that blue sets up the Csound options. I will try once more using the Csound command from blue, but this disables blue's use of Csound control channels.

**Comment by gogins** [comment]
So, here are the instructions for using  blue to render Csound pieces to Jack using the Jacko opcodes:

1. Uninstall previous versions of Csound including Linux packages. You should try to get them all out.
2. Build Csound from current sources: in a build subdirectory, `cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo; make clean; make; sudo make install`.
3. Build the Jacko opcodes from current plugin sources: in a build subdirectory, `cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo; make clean; sudo make install`.
4. Run blue. 
5. Import `jacko_test.csd` and save it as blue project `jacko_test.blue`.
6. **_All rendering will be done as though to a soundfile!!! Even though blue will in fact play real-time audio!!!** In the _Tools_ menu, _Options_ dialog, _Disk Render_ tab, set _Render Method_ to `Commandline Runner`. Set the sampling rate to 48000 (or the same as Jack) and ksmps to 128 (or the same as Jack).
8. In the _Project Properties_ tab of `jacko_test.blue`, set the sampling rate to 48000 (or the same as Jack) and ksmps to 128 (or the same as Jack), and the output filename to `jacko_test.wav`.
9. Now you can use the _File_ menu, _Render to Disk_ command to perform the piece.

Everything should work. The only thing missing here is the ability of blue to send values to Csound control channels using the Csound API.

I know this is an awkward workaround in some ways, but getting further than this will require raising some issues in the blue issue tracker on GitHub. These issues will include:

- [x] Fix the problem of blue's Csound API connection crashing when using the Jacko opcodes. [I submitted an issue to the blue repository about this](https://github.com/kunstmusik/blue/issues/762).
- [ ] Fix the problem that the _Advanced Settings_, _Complete override_ checkbox either does not work, or else it is not sufficiently clear how it works. Does it replace all other settings, or what?

**Comment by gogins** [comment]
See if the problem with blue goes away if I update the memory management scheme.

_No_, same as before: works with command-line renderer, not with API renderer.

**Comment by gogins** [comment]
There was a segmentation violation in opening the Csound webserver opcode library, I deleted that and now the error is:
```
> loading classes from registry
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/home/mkg/blue/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
SCROLL: 0 : 0 : 100
SCROLL: 0 : 0 : 7680
<TOTAL_DUR> = 0.0
<RENDER_START> = 0.0
<PROCESSING_START> = 0.0
Global Duration = 21.0
WARNING: Error opening plugin directory '/usr/lib/csound/plugins64-6.0': No such file or directory
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2a27b5fae5, pid=52419, tid=52447
#
# JRE version: OpenJDK Runtime Environment (18.0.2+9) (build 18.0.2-ea+9-Ubuntu-222.04)
# Java VM: OpenJDK 64-Bit Server VM (18.0.2-ea+9-Ubuntu-222.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x916ae5]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/mkg/csound-webserver-opcodes/build/core.52419)
#
# An error report file with more information is saved as:
# /home/mkg/csound-webserver-opcodes/build/hs_err_pid52419.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
#
```

**Comment by gogins** [comment]
A cursory search does not show the security manager warning as being a cause of crashing.

**Comment by gogins** [comment]
The stack trace from the crash is mostly:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kunstmusik.csoundjni.CsoundJNI.csoundDestroy(J)V+0
j  com.kunstmusik.csoundjni.Csound.delete()V+13
j  blue.csnd6.render.CS6RealtimeRenderService.play(Lblue/BlueData;Lblue/services/render/CsdRenderResult;[Ljava/lang/String;Ljava/io/File;D)V+404
j  blue.csnd6.render.CS6RealtimeRenderService.render()V+176
j  blue.ui.core.render.RealtimeRenderManager.renderProject(Lblue/BlueData;Z)V+137
j  blue.ui.core.render.RealtimeRenderManager.renderProject(Lblue/BlueData;)V+3
j  blue.MainToolBar.renderProject()V+7
j  blue.MainToolBar.lambda$new$1(Ljava/awt/event/ActionEvent;)V+1
j  blue.MainToolBar$$Lambda$288+0x00000008011566f0.actionPerformed(Ljava/awt/event/ActionEvent;)V+5
j  javax.swing.AbstractButton.fireActionPerformed(Ljava/awt/event/ActionEvent;)V+84 java.desktop@18.0.2-ea
j  javax.swing.AbstractButton$Handler.actionPerformed(Ljava/awt/event/ActionEvent;)V+5 java.desktop@18.0.2-ea
j  javax.swing.DefaultButtonModel.fireActionPerformed(Ljava/awt/event/ActionEvent;)V+34 java.desktop@18.0.2-ea
j  javax.swing.DefaultButtonModel.setPressed(Z)V+117 java.desktop@18.0.2-ea
j  javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Ljava/awt/event/MouseEvent;)V+35 java.desktop@18.0.2-ea
j  java.awt.Component.processMouseEvent(Ljava/awt/event/MouseEvent;)V+64 java.desktop@18.0.2-ea
j  javax.swing.JComponent.processMouseEvent(Ljava/awt/event/MouseEvent;)V+23 java.desktop@18.0.2-ea
```

**Comment by gogins** [comment]
Crash report hard to interpret but the error probably happens because of what happens here:
```
SWIGEXPORT void JNICALL Java_csnd6_csnd6JNI_csoundSetMessageStringCallback(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CSOUND *arg1 = (CSOUND *) 0 ;
  void (*arg2)(CSOUND *,int,char const *) = (void (*)(CSOUND *,int,char const *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CSOUND **)&jarg1; 
  arg2 = *(void (**)(CSOUND *,int,char const *))&jarg2; 
  csoundSetMessageStringCallback(arg1,arg2);
}
```

**Comment by gogins** [comment]
I've done as much as I can do on this. Perhaps Steven Yi can find out more
